version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    links:
      - replicate
      - registry
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs
      - ./conf/proxy.conf:/etc/nginx/proxy.conf
    restart: 'always'

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy

  replicate:
    build:
      context: .
      dockerfile: packages/replication-master/Dockerfile
    restart: 'always'
    env_file: .env
    volumes:
       - /usr/local/ipfs-npm-registry-mirror:/usr/local/ipfs-npm-registry-mirror
    environment:
      - VIRTUAL_HOST=replication.registry.js.ipfs.io
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=replication.registry.js.ipfs.io
      - LETSENCRYPT_EMAIL=alex.potsides@protocol.ai
      - NODE_ENV=${NODE_ENV}
      - EXTERNAL_PROTOCOL=https
      - EXTERNAL_HOST=registry.js.ipfs.io
      - EXTERNAL_PORT=443
      - EXTERNAL_IP=35.178.192.119
      - IPFS_STORE_TYPE=s3
      - STORE_S3_REGION=${STORE_S3_REGION}
      - STORE_S3_BUCKET=${STORE_S3_BUCKET}
      - STORE_S3_ACCESS_KEY_ID=${STORE_S3_ACCESS_KEY_ID}
      - STORE_S3_SECRET_ACCESS_KEY=${STORE_S3_SECRET_ACCESS_KEY}
      - STORE_S3_PATH=replication-master
      - FOLLOW_SEQ_FILE=/usr/local/ipfs-npm-registry-mirror/seq.txt
      - CLONE_DELAY=30000
      - FOLLOW_CONCURRENCY=200
      - REQUEST_MAX_SOCKETS=20
    ports:
      - "8080:8080"
      - "4001:4001"

  registry:
    build:
      context: .
      dockerfile: packages/registry-mirror/Dockerfile
    restart: 'always'
    env_file: .env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_HOST=registry.js.ipfs.io
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=registry.js.ipfs.io
      - LETSENCRYPT_EMAIL=alex.potsides@protocol.ai
      - NODE_ENV=${NODE_ENV}
      - EXTERNAL_PROTOCOL=https
      - EXTERNAL_HOST=registry.js.ipfs.io
      - EXTERNAL_PORT=443
      - EXTERNAL_IP=35.178.192.119
      - IPFS_STORE_TYPE=s3
      - STORE_S3_REGION=${STORE_S3_REGION}
      - STORE_S3_BUCKET=${STORE_S3_BUCKET}
      - STORE_S3_ACCESS_KEY_ID=${STORE_S3_ACCESS_KEY_ID}
      - STORE_S3_SECRET_ACCESS_KEY=${STORE_S3_SECRET_ACCESS_KEY}
      - PUBSUB_MASTER=http://replicate:8080
      - REQUEST_MAX_SOCKETS=20
    links:
      - replicate
    ports:
      - "10000-10009:10000"
      - "10010-10019:10001"
      - "10020-10029:10002"
      - "10030-10039:10003"
      - "10040-10049:10004"
      - "10050-10059:10005"
      - "10060-10069:10006"
      - "10070-10079:10007"
      - "10080-10089:10008"
      - "10090-10099:10009"
      - "20000-20100:8080"
